add_rules("mode.debug", "mode.release")

add_includedirs("./", "../")

target("duilib")
    set_kind("static")
    set_languages("c11", "c++14")
    add_defines("_UNICODE", "UNICODE", "_WINDOWS")
    set_pcxxheader("StdAfx.h")
    add_files("StdAfx.cpp", "Uilib.cpp")
    add_files("Animation/*.cpp")
    add_files("Box/*.cpp")
    add_files("Core/*.cpp")
    add_files("Control/*.cpp")
    add_files("Render/*.cpp")
    add_files("Utils/*.cpp")
    add_cxflags("/wd4838", {force = true})
    add_cxxflags("/wd4838", {force = true})
    add_cxflags("/wd4828", {force = true})
    add_cxxflags("/wd4828", {force = true})