add_rules("mode.debug", "mode.release")

add_includedirs("./", "../")

target("base")
    set_kind("static")
    set_languages("c11", "c++14")
    add_defines("_UNICODE", "UNICODE", "_WINDOWS")
    add_defines("NOMINMAX")
    add_files("encrypt/*.cpp")
    add_files("file/file_util_win.cpp", "file/file_util.cpp")
    add_files("framework/*.cpp")
    add_files("hardware/cpu.cpp")
    add_files("network/network_util.cpp")
    add_files("synchronization/lock_win.cpp", "synchronization/semaphore_win.cpp", "synchronization/waitable_event_win.cpp")
    add_files("thread/framework_thread.cpp", "thread/thread_local_win.cpp", "thread/thread_manager.cpp", "thread/thread_win.cpp")
    add_files("time/time_win.cpp", "time/time.cpp")
    add_files("util/*.cpp")
    add_files("win32/*.cpp")
    add_files("third_party/chrome/*.cc")
    add_files("third_party/convert_utf/*.c")
    add_files("third_party/modp_b64/*.cc")
    add_cxflags("/wd4838", {force = true})
    add_cxxflags("/wd4838", {force = true})
    add_cxflags("/wd4828", {force = true})
    add_cxxflags("/wd4828", {force = true})
